services:
  server:
    build:
      context: .
    ports:
      - 9000:80
    env_file:
      - .env
    depends_on:
      - mariadb
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      - MARIADB_DATABASE=myapp
      - MARIADB_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - mariadb-data:/var/lib/mysql

  redis:
    image: redis/redis-stack-server:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  mariadb-data:
  redis-data:
